### ISSUE TITLE
Document the use of miniconda

### ISSUE THREAD

**Issue by adamltyson** [neuroinformatics-unit/neuroinformatics-unit.github.io#304]
There are many issues about documenting the use of conda. I think this means we should actually do it.
- [ ] neuroinformatics-unit/neuroinformatics-unit.github.io#303 
- [x] neuroinformatics-unit/neuroinformatics-unit.github.io#300 
- [x] neuroinformatics-unit/HowTo#18

**Comment by adamltyson** [comment]
With the rise of uv, conda is no longer the obvious choice for all env management. Should we forget documenting it here? I'd rather not write a guide of conda vs uv vs... as this has probably been done far better by others.

**Comment by niksirbi** [comment]
Agreed.
